AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resume-cloud-project-lambda

Globals:
  Function:
    Timeout: 3

Resources:
  ResumeDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-website-tbl
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
  
  ResumeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResumeDynamoDBTable
      PackageType: Zip
      CodeUri: s3://resume-cloud-project-website/resume-function.zip
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        Visits:
          Type: Api
          Properties:
            Path: /visit
            Method: get 

Outputs:
  ResumeLambdaFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for ResumeLambdaFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visit/"
  ResumeLambdaFunction:
    Description: "ResumeLambdaFunction ARN"
    Value: !GetAtt ResumeLambdaFunction.Arn
  ResumeLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for ResumeLambdaFunction"
    Value: !GetAtt ResumeLambdaFunction.Arn