name: Deploy Resume Website to S3

on:
  pull_request:
    types: 
      - closed
    branches:
      - master
    paths:
      - 'resume-website/**'

env:
  BUCKET_NAME: resume-cloud-project-website

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Upload Resume Website to S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload website to S3
        run: aws s3 sync resume-website/ s3://${{ env.BUCKET_NAME }} --delete