name: Cloud Resume Project Deploy

on:
  pull_request:
    types: 
      - closed
    branches:
      - master
    paths:
      - 'resume_function/resume_function.zip'
      - 'templateLambda.yaml'

env:
  AWS_REGION: ca-central-1

permissions:
      id-token: write   # required for requesting the JWT
      contents: read    # required for actions/checkout

jobs:
  test:
    name: Lambda Function Unit Test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest tests/unit/
    
  deploy-lambda:
    needs: test
    name: Lambda Function Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
   
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Upload Lambda package to S3
        run: aws s3 cp resume_function/resume_function.zip s3://resume-cloud-project-website/resume_function.zip

      - name: Deploy Lambda with SAM
        run: | 
          sam build --template templateLambda.yaml
          sam deploy \
          --template templateLambda.yaml \
          --stack-name resume-cloud-lambda \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset